config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :books do
  	resources :reviews
  end
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord 
	# require attr_accessor
	belongs_to :user
	belongs_to :category
	has_many :reviews
	
	has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :book
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :books
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: [:show, :edit, :update, :destroy]
	
	def index
		if params[:category].blank?
			@book = Book.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@book = Book.where(:category_id => @category_id).order("created_at DESC")
		end
		# @books = Book.all
		# render json: Book.all[0]
	end

	def show
		# byebug
	end

	def new
		# @book = Book.new
		@book = current_user.books.build
		@categories = Category.all.map{ |c| [c.name, c.id]}
	end

	def create
		# @book = Book.new(book_params)
		@book = current_user.books.build(book_params)
		@book.category_id = params[:category_id]
		if @book.save
			redirect_to root_path
		else render 'new'
		end
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id]}
	end

	def update
		@book.category_id = params[:category_id]
		if @book.update(book_params)
			redirect_to book_path(@book)
		else 
			render 'edit'
		end
	end

	def destroy
		@book.destroy
		redirect_to root_path
	end

	private

		def book_params
			params.require(:book).permit(:title, :description, :author, :category_id, :book_img)
		end

		def find_book
			@book = Book.find(params[:id])
		end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_book
	before_action :find_review, only: [:edit,:update,:destroy] 

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.book_id = @book.id
		@review.user_id = current_user.id
		
		if @review.save
			redirect_to book_path(@book)
		else
			render 'new'
		end
	end

	def edit
		# @review = Review.find(params[:id])
	end

	def update
		# @review = Review.find(params[:id])
		if @review.update(review_params)
			redirect_to book_path(@book)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to book_path(@book)	
	end

	private
	def review_params
		params.require(:review).permit(:rating,:comment)
	end
	def find_book
		@book = Book.find(params[:book_id])
	end
	def find_review
		@review = Review.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_book.html.erb
<div class="row">
	<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
		<%= image_tag book.book_img.url(:book_show), class: "book_show"%>
	</div>
	<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
		<h2>Title:  	<%= book.title %></h2>
		<h3>Author: 	<%= book.author %></h3>
		<h4>Categorory: <%= book.category.name %></h4>
		<p>Description: <%= book.description %></p>
	</div>
</div>
<div class="row">
	<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
		<!-- For review and rating -->
	</div>
</div>
<%= link_to "Back", root_path %>
<% if user_signed_in? %>

<% if book.user_id == current_user.id %>
<%= link_to "Edit", edit_book_path(book) %>
<%= link_to "Delete", book_path(book), method: :delete, data: { confirm: "Ban chac chu?"} %>
<% end %>
<% end %>

<!-- Hai trang _book.html.erb va show.html.erb giong het nhau, chi khac o cach goi, 
_book.html.erb goi bang cach render 'Book.all', show.html.erb goi bang ham show trong controller,
hien tai chi dung show.html.erb-->

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => {:multipart => true} do |f| %>
	<label>Category:</label> <%=select_tag(:category_id, options_for_select(@categories)) %>
	<%=f.file_field :book_img %>
	<%=f.input :title %>
	<%=f.input :description %>
	<%=f.input :author %>
	<%=f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= simple_form_for @book, :html => {:multipart => true} do |f| %>
	<%=f.select :category_id, @categories %>
	<%=f.file_field :book_img %>
	<%=f.input :title %>
	<%=f.input :description %>
	<%=f.input :author %>
	<%=f.button :submit %>
<% end %>

app/views/books/index.html.erb
<h1 class="current-category"><%= 'Category: ' if !params[:category].blank? %><%= params[:category]%></h1>
<% if @book.count == 0 %>
<h3>Sorry, there is no book here :( </h3>
<% else %>
	<div class="row">
		<% @book.each do |book|%> 
			<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
				<div class="panel panel-default">
					<div class="panel-body">
						<a href="/books/<%= book.id %>">
							<%= image_tag book.book_img.url(:book_index) %> 
						</a>
					</div>
				</div>
			</div>
		<% end %>
	</div>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>
	
<%=render 'form' %>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
		<%= image_tag @book.book_img.url(:book_show), class: "book_show"%>
	</div>
	<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
		<h2>Title:  	<%= @book.title %></h2>
		<h3>Author: 	<%= @book.author %></h3>
		<h4>Categorory: <%= @book.category.name %></h4>
		<p>Description: <%= @book.description %></p>
	</div>
</div>
<div class="row">
	<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
		<!-- For review and rating -->
		<%= render @book.reviews %>
		<div>
			<%= link_to "Add review", new_book_review_path(@book) %>
		</div>
	</div>
</div>
<%= link_to "Back", root_path %>
<% if user_signed_in? %>

<% if @book.user_id == current_user.id %>
<%= link_to "Edit", edit_book_path(@book) %>
<%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Ban chac chu?"} %>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <%= link_to "Library Demo", root_path, class: "navbar-brand" %> 
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% if(user_signed_in?) %>
            <!-- Chỗ này chưa hiểu lắm, phương thức này ở đâu ra nhỉ? -->
            <li><%= link_to "Sign out", destroy_user_session_path , method: :delete %></li>
            <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
          </ul>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Not ready">
            </div>
            <button type="submit" class="btn btn-default">Not ready</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
          <li><a href="/admin">Admin</a></li>
            <% if(user_signed_in?) %>
            
            <li><%=link_to "Add book" , new_book_path%></li>
            <%end%>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Category<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% Category.all.each do |category| %>
                  <li class= "<%=if(params[:category] == category.name) then 'active' end%>">
                    <%= link_to category.name, books_path(category: category.name)%>
                  </li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@book, @book.reviews.build]) do |f|%>
<%= f.input :rating%>
<%= f.input :comment%>
<%= f.button :submit%>
<% end %>

app/views/reviews/_review.html.erb
<p><%= review.rating %></p>
<p><%= review.comment %></p>

<%if user_signed_in? %>

	<%if current_user.id == review.user_id %>
		<%= link_to "Edit", edit_book_review_path(review.book,review) %>
		<%= link_to "Delete", book_review_path(review.book,review), method: :delete, data: {confirm: "Are you sure :("} %>
	<%end%>
<%end%>

app/views/reviews/edit.html.erb
<h1>Edit review</h1>
<%= simple_form_for([@book, @review]) do |f|%>
	<%= f.input :rating%>
	<%= f.input :comment%>
	<%= f.button :submit%>
<% end %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form'%>